version: "3"
services:
    web:
      #image: webmvc:v1
      container_name: ehs-pantau
      build: 
        dockerfile: Dockerfile
        context: .
      ports:
        - "80:80"
      depends_on:
        - db

    db:
      container_name: ehs-db
      image: "mcr.microsoft.com/mssql/server"
      expose:
        - "1433"
      environment:
        SA_PASSWORD: "@Aa123456"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"